name: Visyt
options:
  bundleIdPrefix: com.visyt
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15"
settings:
  base:
    SWIFT_VERSION: 5.9
    PRODUCT_BUNDLE_IDENTIFIER: com.visyt.app
targets:
  Visyt:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Visyt
    settings:
      base:
        INFOPLIST_FILE: Visyt/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.visyt.app
        SWIFT_VERSION: 5.9
    info:
      path: Visyt/Info.plist
      properties:
        CFBundleDisplayName: Visyt
        UILaunchScreen:
          UIColorName: ""
        NSLocationWhenInUseUsageDescription: "Visyt needs your location to show nearby cafes and calculate distances."
        NSUserNotificationsUsageDescription: "Visyt sends reminders before your session ends."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
